sudo: required
services:
- docker
language: go
go:
- 1.9
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH DEBIAN_FRONTEND=noninteractive
  - GPG_NAME=3D86849D
  - GPG_FINGERPRINT=E37EC0B895A9AC27DC4919AB96CEB4B93D86849D
  - secure: gmq5T2xAdQ+R2ri3/vOhX3cfGc47y00mW9rVABm29Wa6K+hgJHDNpoPGvk5EjnKY+a7HdoKTOxKeMz/ddVxcWYc7A3wMN598uVsB9PPAz0YGUlfMch2P4tsAPjGHDViPJ6wLnQYGbBH7wHPCMM32V0xUx7qgjJLjZ3kIJVIlCHCXHwGkoOViiGYga6hty0gPMquhaEnDla8q2P85eFsqh8tHDULlT4jwxiYB9xOdjiLqxkSNJpRUxy5pSCawUbteioZjyKkrr5j3+uhLjKPc4C3bD+i6OfgjOH6s+v1qVGWszdksNa3FyV//UqIdpqHgki8R8Ml5GENuXrXZG1VHFXIbIMh02Oss9cLCd+D9CiXGlvOOcWmndp94S8pQbxjf9Ug9iYvn1VOjglOYXy8ThRCdMJBDlRxwefZ7nPmcNiSVQvVbSiQH9UrWVFk9+4LZ7FtcoNPkL+jkpSQIUbYHKArZDoxbXy5CgdoeJbOHVGHoJG5cP+W72StT2ZRkMQ0aFSm+DeYYjzti4LZPOaysN5UlxgK4VnbNxODevb5jVRQrSeO018aICeRpPETXK35ZlGy+Lscon5D1uINHMP+oYUijsHKd/YeXU4iVN/QuuGWL+a58tTKleR8ONxcatlBkiPkkZ90dGOIMTSiKQDwJSM7i8ism9CKLMWx5Ql4o19I=
  - secure: DPs24EcsNePzhDsfPcwz+38IprF4UogGKHVcexwHSWay1Fy+Zit7jyAy+ltUFFqbWXsdCuMMfA/Db06sVZc5Z/X+4kcdDdlpmPjWxtPlGHu8saAXqkaIAVn0lQy582c46sWsebM2JSksYTYkQ8lxofGMIIsh+xsaeVx/Bw1dGFrCgGwvjtiALqU1aNbDQ5CEQIDjXxnm702xs3VI8K0BEXxuHIErUgrXk2LsWakiRe3+nlu3Gh5NycDKJGThOqdE0F+nqC33qiiVZDaPkAqm/REW0fnN4+evCKW9VOClwMsqzOwQeNFV8G/tumKqhAHAZ4L8TpS4fyaeSh9fSlKpz1jPRS/BnIP0P31hwyI47/GLZd7+TdspySr8yJKa3Lr8Oh1r8rzjW1o/L/65UrH2fkOtEgSEv3j7zJAqs5nhQixtMssSB1L0DcuLAjSehMxdwBxFFQ1Zdhb8fl2N4itHOwnIv0JDWjpjc+Y30fDvEAVmctjIqdN7gK+9+MOrOtbPg77+WCPKuTGUqHhyCWG/nUejzflKBvrO3rIPdK3MCKGnVwg9npsWQbxxs9sjhBPSOVAVqg4I6EQ7y+BFCmHpCAo5oj1QJ/XzV4W7heZpJJkjG3WSLm6DeoVr/CDotayoDbPR2fYTa7wqUBxXRzu5CXeaZvaQXN5BekiaI9uLfH0=
  - secure: 2Fjhnc3yivBiACXyiZvs9zDrrHzZKEVspjr4kkQfUlR5TzzRToImWZ5wcj3cd7YPbh0wROYK9P75Yq06O0EdwHcQH2llssybO7ht0Ct0Qjz8uRglI2XtNmnwMh1S9bStIkYYuIkk2UsMq3WKHUm0P038HY4tTGUu/laKmZyVpDMD/C6c4qjA7MrtbyadGrbs5X8VH38r6fFyHxL7T5eJ18/5dRoV72TCKl3aYeIWl18gHHH31cvgFo5TkhGCiqs4jOi7jBjAjLSsoCs6+WU1ugoZdXW453QMsrU92Uskeq6zf/tV+Hr5A686JQBIe3O+LQDntrfda8rfrP5v2vj/yJr87kO7olQKUr2YSeMHQd+OE0l7cxMgFTXkTqG2uaMPREA9yxA86A/qr21lzRJGjKQO6q3qBUnJBdG7Oc2f/KX3spcE4KVcdRaSLpXKfEBkOtkWwl1nfnq7QTKGOgblipS4ggNYSW3WPqpoyxCdyA682lpZ6i2w1jIQnuLGp18hPiQNcWYwHq1VKmwvPIEcDV98IdAvXZKKx/4N0FY9Z96Nv1kIO/saJqgQeL9AYXT+U/N3zSQbse93ZaS3vyZ231u/7NQM3pPfbNg0Ue5P+EbVDZdFHI0dhd8ty5f+dTNj0YadrnAuY1nvvd07N36ojxMKjIlajZBtKiCQm0QQi1M=
  - secure: psWBrKFfQ1e6Zc+ztzG3RGQhPckmyDc368jLUknlupivciwRolNKDohEoW4ooCt40uo0PahbZQ0EtZBT39wda+AMYVHRwbeflbOt55DftI4078qN6Hymxu3CWM4M37Xv1kaTsAXMl0GwNcp3CddkS8NkblS6CPFp/WrcEtpYNk5bYMG1aGm9AEi7Kp8zlgY22IDMJvXqMxkTZz6Ck++3DNXC5jr2AmjkMReuvUefJ8SOFt48s7Q1M/tlS5EL+dMqd6nMqCr5UCkGErBwvG8+wDvJ7G7tZ7jRt4bB0Plqu8C8zC8es87FCsAcP0I4HbN8Spk4JmzPoDZy/je9TsciNSngNzhOvN0LDyN+MrWp4wIYOqffYX8A6jXNOYbSFDrQoqjf7c/rnae+7A23SrXEvHBTMl+TmnaX7QrIZs6OFsXzJQA+v8sRz2c3Gu5MK+w+84eDuqwhhuacTU26PuEPlrJI7/72q7JyzlQ0Yg21lsLuvFrTXZ6/lpfz33u4+Hfz6ruVNY9NU6vsO5npESesno3sUs5gwWFeR6kS7vY/jISRjqN4IiTO83LKKYDVK/SFmXSHF5epu30IokqnRZ7P7zsRvgty2IgAwJsoo3r84Czcky5aTFKYf4n7+3PIvrxyIPRxjsHYgrrJBB27TfivR/idbhGpeaTfbz9bCMMNucg=
  - secure: yA72Vj7eKHgU+x5nuCdb2aQnreGLWzqur61HRSFMgtd4Gx7+r8OBY7CVpjifOjAPuTCLwqkiwpCmaaBnQlbIRlBX0CT1akARjn4FsrITvMwGeZDBy+SqhA2qXsUPNGMye5oSp1TnESsAi5tk9Jg7E8LKefggez9opUkcUATyb/D23kjaouKR587eS46jL0n6hDX65jZlSZOOAOK8IiUJ3HFjoJ+YB0To4zQ+jbbQCX3Jp6gTQGLdmmE/flAIJPS+5iZXVjhSQmf5vqscTPbFigEt4XMFo0dFV5HlZMopDs+I7YQMKVEyOuphd965yOS0OdMTdIchykIMUyISBIDaTgbG+oDLyBfsothps5Xcqp3MiGxyWoyHQzQo5TjvjF1YVtw35sv3ExfH/H5pxxjehrwGy6KpWrKHXVjIsT7/LOZ9Ps4w1hkHWCimChouXwJUA3l2L/rq1XA6PANIPIKPEe9k6B689gxjzWL/wqcvO9M6wVc7iW/J/JWn5QiH0ZKUPXeoZJImF158Xq/w8mol1Aryp8ZIk+dUcT3blHGXpBafqTHp5nmpNiuaj1lH2t3kueSESM5DH+3lidWskbWyi9tg2svL2wq8qMIC/UZCiKVc731cRLUsQC6r5liSRmd5S9RZVaBlCqmda5u8sZ3doxzOivQdN84t1NAqJ7e2xEo=
  - secure: DOXSY9a4M4Nc8ameRqQQuGZ0k0fvMugX4MaJxJwRnHRl7lWpgN1zGikID+Oy1ronvaJ/bRlXltlrSmdiPdY+ZiNgJ/Pw9BddtROuejx506Md5gjncOKqEdx6IxjSAGZuTqFGc3vss75thok853m4HhqUHIhuRnMq+RrZ9t0j9uhrI9oaB6voWWZnrzlpKip38/lDhW1q/ub/eNnYvC5pJenEjZBlPre7Y7rWg7wRU0mZ/O+g/Ob11nTd805JX0XxR2r7nC+4foGRrxalUn656B++mTrpc8uunYiKt1VXHbNZWCVvcXVTKvxGoh7ZN8gpKr9zYE5VQa0pOb3m3kTczNZvTLzNyQ333oqTBWIZ+JxsYpiKU2/n9LSYYadBjQR/N8mQVq/eCpxZPL1NbnyFKM27u400eeyzNellFskzp5z2JAb4aS6CNOTiRqPyVkK5i8YqhM7UfVn0swKuC5AB6v18fR47Aq0JqbkHFjth2w3K5Wr0D4M+l+qnqu+f34Y6P5k8pNdZTH+o8YcanP0XCZJPUzcO9Ort6BDgXEw9SNENk4IG+PGLB7805Gr1YgV1PvTZ/m1/LNPgmPbX9xTYLUlakxaqq7XoHV3JmeszT5KNOTUjEYpFATafM0b4S5cXzlRLwLmid8Q3PGT1TaSY8Wy0s0usGKzH2sFbaZAvA8Q=
addons:
  apt:
    packages:
    - devscripts
    - debhelper
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_7a84e1e19ced_key
  -iv $encrypted_7a84e1e19ced_iv -in usacloud_gpg_key.enc -out usacloud_gpg_key -d;
  fi
- go get -u github.com/golang/lint/golint
install:
- make gen-force
script:
- make test
- make lint-docs
- make docker-build
before_deploy:
- docker pull sacloud/rpm-build:latest
- docker pull sacloud/deb-build:latest
- make rpm deb
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub
  && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=1000
- git fetch --tags --depth=1000 || true
deploy:
- provider: script
  script: scripts/usacloud-release.pl --task=upload-to-github-release && scripts/usacloud-release.pl
    --task=upload-master-to-github-release && scripts/release_homebrew.sh && scripts/release_docker_image.sh
    && scripts/release_website.sh
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: scripts/usacloud-release.pl --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
notifications:
  slack:
    secure: HXcmuKet1AgRIlgLZk8ERedRse6zF0a0nqxEpo0CysFqLm+/Gv4FljH4WTIcRYqvCicTnd0ULp8A8/b40ZO6eScQ/CQqTMUWvA2wDh5hFstOwFQAVYsE0tQ1f2R55PnapWZ+fXJNlvTWt2qNPaVtBWAcZO8yYBAvayzU6ye3QsB5Youe3nCyvTru8hmaidjfSFb7nf5pB945Zmr3iiSWTTsYIYWRO5OXk46kQMMx7uRjjVrFkHJfQjQXCXtRaeq8VyT3L1zpmdqeJboA/ds8M6cndV3YccVd6dGrRa009b4+pFiOX/kXqGjBzcjS3j17d1ZN5cX5rFdZFyBJSCbggVXmLOOQjJVwylVv1BayWnWxUCYnKLun1vGRj+OQWt+TGZ6lNMB7GBdxuYf+JRXNGW7V4H9weYANo/ueTe37Q36nzilHDw9k0WBVT3o04EZuU7lfUt9Gkegd3FkHUcLE58fUf/owPBKeGM8vwmwfi2jaJsME1qr9iGakgnr13HIbRL7DQW0H7tWaKV+AjtzgUdw5htMhHMqjlMpA+6VJSu0UgMs/+504cDiwjA7/VeMYf1GlG/hRwUMLwcaifxqbdxax/Qklvz+eBL0h0Z6JLKcreaqd2shlszvo+n6lbTQS5OywU3uhBPpeNr5Km4SbVX6+1wbhdeOHWrQ/3lXneik=
